# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gamelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=10)),
                ('game_name', models.CharField(max_length=20)),
                ('game_link', models.CharField(max_length=100)),
                ('game_title', models.CharField(max_length=100)),
                ('game_picture', models.CharField(max_length=300)),
                ('game_nickname', models.CharField(max_length=100)),
                ('game_time', models.FloatField()),
                ('game_count', models.FloatField()),
            ],
        ),
    ]
