# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_tvlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvlist',
            name='tv_name',
            field=models.CharField(max_length=100),
        ),
    ]
