# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0006_laterlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laterlist',
            name='movie_people',
            field=models.FloatField(),
        ),
    ]
