# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0008_auto_20161227_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='moviesuggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_link', models.CharField(max_length=100)),
                ('movie_score', models.FloatField()),
                ('movie_pic', models.CharField(max_length=100)),
            ],
        ),
    ]
