# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0009_moviesuggest'),
    ]

    operations = [
        migrations.CreateModel(
            name='oraerror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.CharField(max_length=100)),
                ('error_message', models.CharField(max_length=100)),
                ('error_cause', models.TextField()),
                ('error_action', models.TextField()),
            ],
        ),
    ]
