# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0011_auto_20170104_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='matchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=100)),
                ('match_address', models.CharField(max_length=100)),
                ('match_date', models.CharField(max_length=20)),
                ('movie_website', models.CharField(max_length=500)),
                ('movie_count', models.CharField(max_length=100)),
                ('movie_detail', models.CharField(max_length=500)),
            ],
        ),
    ]
