# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0012_matchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchlist',
            old_name='movie_count',
            new_name='match_count',
        ),
        migrations.RenameField(
            model_name='matchlist',
            old_name='movie_detail',
            new_name='match_detail',
        ),
        migrations.RenameField(
            model_name='matchlist',
            old_name='movie_website',
            new_name='match_website',
        ),
    ]
