# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0014_lyrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyrics',
            name='lyric_name',
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='lyric_pic',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='lyric_url',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
